---
- hosts: ['devel_centos8', 'stable_centos8']
  name: Install and configure Python 3 for rpmlint and nodejs
  become: True

  tasks:
    - name: Install Python 3 packages
      dnf:
        name: python3
        state: present

    - name: Update path to /usr/bin/python
      alternatives:
        name: python
        path: /usr/bin/python3
        

